[tox]
minversion = 2.0
skipsdist = True

[testenv]
usedevelop = True
deps = -r{toxinidir}/requirements.txt

setenv = LANGUAGE=en
whitelist_externals = sh
allowlist_externals = *
commands =
    python hass.py
